26 create individual activity UI
SQA-Group-1/feel_good_inc pull request #41
Opened 2023-11-06 20:23 UTC by Woodhouse15

2023-11-08 21:24 UTC, Woodhouse15 commented
Add activities and their functionality

2023-11-08 21:53 UTC, nimitz-Bear requested changes
In general, for the `Fragment`s you create for the calming activities, it could be a good idea to create a sub-directory under `/fragments`, something like `calming_activities` to  ensure that all the related fragments are all kept in the same place.

Also, for the `Fragment`s' XML files, `grounding_fragment.xml`, `breathing_fragment.xml` and `sleep_fragment.xml`, it could be good to have a sub-directory in the `/layouts` folder for them.

Overall, quite good, especially for an issue this big. 

It's just a matter of some minor javadocs missing, and moving some of the fragment `.java` and `.xml` files together, so they're more maintainable.

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/activityRecyclerView/ActivityData.java
This should probably go in `/Models`, and perhaps be renamed to `Activity`

Also, need some Javadoc explaining what the class does

Lastly, for `estimatedTime`, what kind of time does it need to be seconds? milieseconds?

Also, for `imagePath`, relative to where? Where should images typically be stored?

Probably worth adding comments for those.

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/activityRecyclerView/ActivityViewHolder.java
my gut tells me this shouldn't be a separate Java file. Maybe it should be in the same file as the rest of the parts of the recycler view (and the fragment/activity) that the view is in?

Not sure what the official best practice is for `RecyclerView` though.

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/activityRecyclerView/ClickListener.java
I really do feel like this also doesn't need to be a separate java file just for 12 lines of code

Then again, I'm also not sure what the best practice is for this.

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/adapters/ActivityGalleryAdapter.java
> +public class ActivityGalleryAdapter extends RecyclerView.Adapter<ActivityViewHolder> {
A quick javadoc description here would be good

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/ActivityFragment.java
Put this in a sub-directory with the other fragments you created?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/BreathingFragment.java
Put this in a sub-directory with the other fragments you created?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/GroundingFragment.java
Put this in a sub-directory with the other fragments you created?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/SleepFragment.java
Put this in a sub-directory with the other fragments you created?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/drawable/birds.jpg
![image](https://github.com/SQA-Group-1/feel_good_inc/assets/106123286/6dd273da-52f8-45ab-8748-3290bae57a5b)

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/drawable/circle_shape.xml
I have literally no idea how these work so I'm gonna go with the good old: LGTM

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_mood.xml
Thanks for changing these :)

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_grounding.xml
Put into a `layout/calming_activities` sub-folder?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_breathing.xml
Put into a `layout/calming_activities` sub-folder?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_activity.xml
Put into a `layout/calming_activities` sub-folder?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_sleep.xml
Put into a `layout/calming_activities` sub-folder?

2023-11-08 21:53 UTC, nimitz-Bear commented on app/src/main/res/values/strings.xml
Thanks 🥇

2023-11-09 17:53 UTC, nimitz-Bear approved these changes
LGTM

2023-11-09 17:55 UTC, merged