3 login
SQA-Group-1/feel_good_inc pull request #55
Opened 2023-11-07 11:15 UTC by MC72144

2023-11-10 22:27 UTC, nimitz-Bear requested changes
There are a couple of changes.

- [ ] Also, `LoginActivity` and `SignupActivity` have some backend functions in them. It's best practice to put them into a seperate `Service` called `LoginService` (probably a `Service` bound to an `Activity`)
- [ ] remove any eclipse files/directories like `.settings` to avoid any issues. These should potentially be added to the .gitignore as well to avoid issues in future.
- [ ] Refactor `LoggedInUser`, by:
     - [ ] moving it to the `app/src/main/Models` folder with the other data models
     - [ ] refactoring it to be a general `User` model, which can be re-used better later on (with an `isLoggedIn` bool)
- [ ] Add some comments to the modified `build.gradle` files to delineate where the login/signup firebase dependencies come in
- [ ] (OPTIONAL, but recommended) Create an activity-bound `Service` that combines `LoginDataSource` and `LoginDataRepository`, `Login` Activity's `loginUserAccount()` and Signup's `registerNewUser` into a single `Service`.

2023-11-10 22:27 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/database/Result.java
Again, not really sure what this is doing. To me, it looks like generics are being used just to print out the error/success of a class. Wouldn't we be better off just getting the `Result` data directly from the `LoggedInUser` model?

2023-11-10 22:27 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/models/LoggedInUser.java
This file should probably be with the other `app/src/main/Models`.

Also, wouldn't it make more sense to have a generic `User` model, then just have a bool as well for if they're logged in or not?

2023-11-14 10:32 UTC, nimitz-Bear approved these changes
Overall fine, it's just adding more documentation to the `UserService` to make it more clear how this should be used

2023-11-14 10:32 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/database/JournalDatabaseHelper.java
> +        // journalsRef = firestore.collection("users").document(User.getCurrentUserKey()).collection("journals");
I'll probably need to add this back in later on

2023-11-14 10:32 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/services/UserService.java
> +public class UserService extends Service {
It'd be good to have an example of how to use the service here in the Javadoc. Surround the code example with `<pre>  </pre>`

2023-11-14 10:35 UTC, nimitz-Bear approved these changes

2023-11-14 10:37 UTC, Woodhouse15 approved these changes
👍

2023-11-14 10:37 UTC, merged