50 fix initial linter errors
SQA-Group-1/feel_good_inc pull request #57
Opened 2023-11-08 15:29 UTC by nimitz-Bear

This pull request adds a linter to the pipeline. The linter also has a `lint.xml` file in the project root that is used to disable some of the more unnecessary linter errors.

**Steps Done**
- [x] created an `android-lint.yml` CI workflow file that handles running the linter on the pipeline
- [x] fixed all of the errors in `main` to ensure that the CI workflow would pass
- [x] Should add a template to pull requests

**Future Additions**
- [ ] create a formatter to ensure that code can be easily changed to comply with the linter

2023-11-08 21:22 UTC, silfeh requested changes
some areas that are commented out in the code may need to be looked at.

2023-11-08 21:22 UTC, silfeh commented on .github/workflows/android-lint.yml
> +#          path: '**/build/reports/lint-results-*.html'
should this commented section be left in?

2023-11-08 21:22 UTC, silfeh commented on .github/workflows/android.yml
> +#      run: ./gradlew lint
also here

2023-11-08 21:22 UTC, silfeh commented on app/src/main/res/values/strings.xml
> +<!--    <string name="hello_blank_fragment">Hello blank fragment</string>-->
remove this placeholder instead of commenting probably

2023-11-08 21:22 UTC, silfeh commented on lint.xml
> +    <!-- Ignore the ObsoleteLayoutParam issue in the specified files -->
also remove comments here if unneeded

2023-11-08 21:58 UTC, nimitz-Bear commented
@silfeh should be good now

2023-11-10 12:23 UTC, silfeh approved these changes
looks good thank you

2023-11-10 15:33 UTC, merged