Resource page child pages
SQA-Group-1/feel_good_inc pull request #70
Opened 2023-11-15 21:59 UTC by saamiyaAqeel

2023-11-16 13:25 UTC, nimitz-Bear requested changes
Thanks, this makes the app a lot more fleshed out. Most of the changes requested here are minor, just for code readability/better user experience

- [x] Put all the resources `Fragment`s in a `../fragments/resource` folder
- [ ] lots of strings are hardcoded, instead of in the strings.xml. You can run `./gradlew lint` in terminal to see where they are.
- [ ] Make links like www.helplink.com actually redirect to web-pages, if possible.
- [ ] Some .xml elements like `textview5` have arbitrary names, instead of meaningful ones like `supportGroupDescription`
- [ ] a back button, going back to the parent resource page, from each of the child pages would be a lot better for user experience

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/EducationResources.java
> +    public static EducationResources newInstance(String param1, String param2) {
What are `param1` and `param2` actually for? probably should delete them if they don't do anything

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/SelfHelpStrat.java
> +        args.putString(ARG_PARAM1, param1);
Also not sure what `param1` and `param2` do here, probably auto-generated?

Should just remove them so we don't have any extra variables in the code.

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/SupportGroup.java
> +            mParam1 = getArguments().getString(ARG_PARAM1);
Remove `param1` and `param2` here too if they don't do anything

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/emergencyHotline.java
Rename this file from `emergencyHotline` to `EmergencyHotline`, to abide by java conventions

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/java/com/example/feelgoodinc/fragments/emergencyHotline.java
> +        args.putString(ARG_PARAM2, param2);
Remove `param1` and `param1` if not used

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_education_resources.xml
In General, this file has a lot of strings that are hardcoded, which is bad practice, especially if we want to convert our code to work for differnet languages.

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_education_resources.xml
> +        android:text="Education"
Example fo some hard-coded stirngs

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_education_resources.xml
> +        android:text="Podcasts"
Another hard coded string

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_education_resources.xml
> +        android:text="www.articles.com"
If possible, make links like this clickable.

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_emergency_hotline.xml
Change strings from hardcoded to strings.xml

Make links clickable, if possible.

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_self_help_strat.xml
Change strings from hardcoded to strings.xml

Make links clickable, if possible.

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_support_group.xml
> +        android:text="Depression Fighters"
This sounds like Foo fighters but worse

2023-11-16 13:25 UTC, nimitz-Bear commented on app/src/main/res/layout/fragment_support_group.xml
Notably, this file features some cases of elements with auto-generated names like `textView5` instead of more meaningful names.

Change strings from hardcoded to strings.xml

Make links clickable, if possible.

2023-11-24 10:33 UTC, nimitz-Bear approved these changes

2023-11-24 10:38 UTC, Woodhouse15 approved these changes

2023-11-24 10:39 UTC, merged